<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_LexicalData extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'lexical_data', array('language_id','lexical_feature_id','bib_source','bib_source_pages','original_form','phonemicized_form','relationship_type_id','gloss_in_bib_source','loan_source_language_id','etymology_note','phonology_note','grammatical_note','semantic_note','general_note','phylogenetic_code'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
}